trigger:
- master

variables:
  NAME: spirv

jobs:
- job: Build
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-16.04
      #MacOS:
      #  vmImage: macOS-10.14
      #  MACOSX_DEPLOYMENT_TARGET: '10.13'
      #Windows:
      #  vmImage: vs2017-win2016
  pool:
    vmImage: $(vmImage)
  steps:
  - task: UsePythonVersion@0
    displayName: Select Python 3.6
    inputs:
      versionSpec: '3.6'
  - task: Bash@3
    displayName: Install development requirements
    inputs:
      targetType: inline
      script: |
        python -m pip install -U pip setuptools wheel
        pip install black flake8 pytest flit
        wget -qO - http://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.1.130-xenial.list http://packages.lunarg.com/vulkan/1.1.130/lunarg-vulkan-1.1.130-xenial.list
        sudo apt update
        sudo apt install vulkan-sdk
  - task: Bash@3
    displayName: Lint (black)
    inputs:
      targetType: inline
      script: |
        black --check .
  - task: Bash@3
    displayName: Lint (flake8)
    inputs:
      targetType: inline
      script: |
        flake8
  # - task: Bash@3
  #   displayName: Build wheel and install in development mode
  #   inputs:
  #     targetType: inline
  #     script: |
  #       python setup.py develop
  #       python setup.py bdist_wheel
  # - task: Bash@3
  #   displayName: Test
  #   inputs:
  #     targetType: inline
  #     script: |
  #       pytest --disable-warnings --junit-xml=results.xml || true
  #
  #       # Fail the task if results.xml was not created
  #       if [[ ! -f results.xml ]]
  #       then
  #         echo "##vso[task.logissue type=error]No test results were found"
  #         exit 1
  #       fi
  # - task: PublishTestResults@2
  #   inputs:
  #     testResultsFiles: results.xml
  #     mergeTestResults: true
  #     failTaskOnFailedTests: true
  #     testRunTitle: Test $(vmImage)
  - task: Bash@3
    displayName: Test (packaged)
    inputs:
      targetType: inline
      script: |
        flit install
        rm -rf ./spirv ./build ./egg-info
        pytest --disable-warnings --junit-xml=results-packaged.xml || true

        # Fail the task if results-packaged.xml was not created
        if [[ ! -f results-packaged.xml ]]
        then
          echo "##vso[task.logissue type=error]No test results were found"
          exit 1
        fi
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: results-packaged.xml
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: Test $(vmImage) (packaged)

